///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace DesktopDemo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the DesktopDemoRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("40d96d78-483a-4872-a544-c44443639ee7")]
    public partial class DesktopDemoRepository : RepoGenBaseFolder
    {
        static DesktopDemoRepository instance = new DesktopDemoRepository();
        DesktopDemoRepositoryFolders.FormVipApplicationAppFolder _formvipapplication;

        /// <summary>
        /// Gets the singleton class instance representing the DesktopDemoRepository element repository.
        /// </summary>
        [RepositoryFolder("40d96d78-483a-4872-a544-c44443639ee7")]
        public static DesktopDemoRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public DesktopDemoRepository() 
            : base("DesktopDemoRepository", "/", null, 0, false, "40d96d78-483a-4872-a544-c44443639ee7", ".\\RepositoryImages\\DesktopDemoRepository40d96d78.rximgres")
        {
            _formvipapplication = new DesktopDemoRepositoryFolders.FormVipApplicationAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("40d96d78-483a-4872-a544-c44443639ee7")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The FormVipApplication folder.
        /// </summary>
        [RepositoryFolder("40a3c487-18cb-407a-bf25-6161df0a8849")]
        public virtual DesktopDemoRepositoryFolders.FormVipApplicationAppFolder FormVipApplication
        {
            get { return _formvipapplication; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class DesktopDemoRepositoryFolders
    {
        /// <summary>
        /// The FormVipApplicationAppFolder folder.
        /// </summary>
        [RepositoryFolder("40a3c487-18cb-407a-bf25-6161df0a8849")]
        public partial class FormVipApplicationAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _vipdatabaseInfo;
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _lastnameInfo;
            RepoItemInfo _musicInfo;
            RepoItemInfo _rbmaleInfo;
            RepoItemInfo _btaddInfo;
            RepoItemInfo _btclearInfo;
            RepoItemInfo _closeInfo;
            RepoItemInfo _vipcount1Info;

            /// <summary>
            /// Creates a new FormVipApplication  folder.
            /// </summary>
            public FormVipApplicationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FormVipApplication", "/form[@name='formVipApplication']", parentFolder, 30000, null, true, "40a3c487-18cb-407a-bf25-6161df0a8849", "")
            {
                _vipdatabaseInfo = new RepoItemInfo(this, "VIPDatabase", "titlebar[@accessiblerole='TitleBar']", 30000, null, "98f0380b-f6ad-4d08-8402-ebad7d64b069");
                _firstnameInfo = new RepoItemInfo(this, "FirstName", "?/?/text[@accessiblename='First Name:']", 30000, null, "f1a68154-94d0-44c2-9d3a-a08868923bea");
                _lastnameInfo = new RepoItemInfo(this, "LastName", "?/?/text[@accessiblename='Last Name:']", 30000, null, "9fffe305-456c-4acf-9ff1-abc709afc635");
                _musicInfo = new RepoItemInfo(this, "Music", ".//listitem[@accessiblename='Music']", 30000, null, "20325ad0-c19c-4475-b1d2-e97c2c58ba85");
                _rbmaleInfo = new RepoItemInfo(this, "RbMale", "?/?/radiobutton[@name='rbMale']", 30000, null, "729abdf0-5020-4443-926e-074aeb88e1e9");
                _btaddInfo = new RepoItemInfo(this, "BtAdd", "button[@name='btAdd']", 30000, null, "9c9860cf-cb5d-4260-94fb-dd009bb3b555");
                _btclearInfo = new RepoItemInfo(this, "BtClear", "button[@name='btClear']", 30000, null, "e14541ae-ef69-4f3d-ac2b-ecff2b9b5634");
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/button[@accessiblename='Close']", 30000, null, "e0a9772c-2a37-4569-ba35-00f5efb3a20d");
                _vipcount1Info = new RepoItemInfo(this, "VIPCount1", "?/?/text[@accessiblename~'VIP count:']", 30000, null, "4fccbef9-60c2-4f9b-b055-bc3a0778775c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("40a3c487-18cb-407a-bf25-6161df0a8849")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("40a3c487-18cb-407a-bf25-6161df0a8849")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The VIPDatabase item.
            /// </summary>
            [RepositoryItem("98f0380b-f6ad-4d08-8402-ebad7d64b069")]
            public virtual Ranorex.TitleBar VIPDatabase
            {
                get
                {
                    return _vipdatabaseInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The VIPDatabase item info.
            /// </summary>
            [RepositoryItemInfo("98f0380b-f6ad-4d08-8402-ebad7d64b069")]
            public virtual RepoItemInfo VIPDatabaseInfo
            {
                get
                {
                    return _vipdatabaseInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("f1a68154-94d0-44c2-9d3a-a08868923bea")]
            public virtual Ranorex.Text FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("f1a68154-94d0-44c2-9d3a-a08868923bea")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The LastName item.
            /// </summary>
            [RepositoryItem("9fffe305-456c-4acf-9ff1-abc709afc635")]
            public virtual Ranorex.Text LastName
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LastName item info.
            /// </summary>
            [RepositoryItemInfo("9fffe305-456c-4acf-9ff1-abc709afc635")]
            public virtual RepoItemInfo LastNameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }

            /// <summary>
            /// The Music item.
            /// </summary>
            [RepositoryItem("20325ad0-c19c-4475-b1d2-e97c2c58ba85")]
            public virtual Ranorex.ListItem Music
            {
                get
                {
                    return _musicInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Music item info.
            /// </summary>
            [RepositoryItemInfo("20325ad0-c19c-4475-b1d2-e97c2c58ba85")]
            public virtual RepoItemInfo MusicInfo
            {
                get
                {
                    return _musicInfo;
                }
            }

            /// <summary>
            /// The RbMale item.
            /// </summary>
            [RepositoryItem("729abdf0-5020-4443-926e-074aeb88e1e9")]
            public virtual Ranorex.RadioButton RbMale
            {
                get
                {
                    return _rbmaleInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RbMale item info.
            /// </summary>
            [RepositoryItemInfo("729abdf0-5020-4443-926e-074aeb88e1e9")]
            public virtual RepoItemInfo RbMaleInfo
            {
                get
                {
                    return _rbmaleInfo;
                }
            }

            /// <summary>
            /// The BtAdd item.
            /// </summary>
            [RepositoryItem("9c9860cf-cb5d-4260-94fb-dd009bb3b555")]
            public virtual Ranorex.Button BtAdd
            {
                get
                {
                    return _btaddInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtAdd item info.
            /// </summary>
            [RepositoryItemInfo("9c9860cf-cb5d-4260-94fb-dd009bb3b555")]
            public virtual RepoItemInfo BtAddInfo
            {
                get
                {
                    return _btaddInfo;
                }
            }

            /// <summary>
            /// The BtClear item.
            /// </summary>
            [RepositoryItem("e14541ae-ef69-4f3d-ac2b-ecff2b9b5634")]
            public virtual Ranorex.Button BtClear
            {
                get
                {
                    return _btclearInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtClear item info.
            /// </summary>
            [RepositoryItemInfo("e14541ae-ef69-4f3d-ac2b-ecff2b9b5634")]
            public virtual RepoItemInfo BtClearInfo
            {
                get
                {
                    return _btclearInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("e0a9772c-2a37-4569-ba35-00f5efb3a20d")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("e0a9772c-2a37-4569-ba35-00f5efb3a20d")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }

            /// <summary>
            /// The VIPCount1 item.
            /// </summary>
            [RepositoryItem("4fccbef9-60c2-4f9b-b055-bc3a0778775c")]
            public virtual Ranorex.Text VIPCount1
            {
                get
                {
                    return _vipcount1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The VIPCount1 item info.
            /// </summary>
            [RepositoryItemInfo("4fccbef9-60c2-4f9b-b055-bc3a0778775c")]
            public virtual RepoItemInfo VIPCount1Info
            {
                get
                {
                    return _vipcount1Info;
                }
            }
        }

    }
#pragma warning restore 0436
}